version: '3.2'
services:
  listener:
    command:
    - sleep
    - "9999999999"
    tty: true
    stdin_open: true
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    build: 
      context: .
    volumes:
    - bundle-data:/app/vendor/bundle
    - type: bind
      consistency: cached
      source: .
      target: /app/

volumes:
  bundle-data:
