version: 2.1

jobs:
  release_image:
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:v1.0.6
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
      REGISTRY_REPO: library/scholarsphere-metadata-listener
      DOCKER_USERNAME: 'robot$circleci'
      GITHUB_USER: 'psu-stewardship-bot'
    steps:
      - add_ssh_keys
      - run:
          name: "Release"
          command: |
            /usr/local/bin/tag-image
  build:
    docker:
      - image: devago/docker-compose
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
      REGISTRY_URL: harbor.k8s.libraries.psu.edu/library/scholarsphere-metadata-listener
      DOCKER_USERNAME: 'robot$circleci'
    steps:
    - setup_remote_docker:
        version: 19.03.12
    - checkout
    - run:
        name: "Build Docker Container"
        command: |
          echo "export BASE_HASH=`git rev-list --max-count=1 HEAD Gemfile Gemfile.lock Dockerfile|sha256sum|cut -c1-8`" >> $BASH_ENV
          source $BASH_ENV
          docker pull $REGISTRY_URL:$BASE_HASH || docker build -t $REGISTRY_URL:$BASE_HASH . 
          docker build --build-arg BASE_HASH=${BASE_HASH} -t $REGISTRY_URL:$CIRCLE_SHA1 -f Dockerfile-ci .
    - run:
        name: "Niftany"
        command: |
          docker run $REGISTRY_URL:$CIRCLE_SHA1 /app/bin/niftany
    - run:
        name: "RSpec"
        command: |
          export TAG=$CIRCLE_SHA1
          docker-compose -f docker-compose.yml -f docker-compose-ci.yml run --name ci --service-ports ci /app/bin/rspec-ci -p ci
    - run:
        name: "Publishing the image"
        command: |
          source $BASH_ENV
          docker login -u $DOCKER_USERNAME -p $HARBOR_PASSWORD $REGISTRY_HOST
          docker push $REGISTRY_URL:$BASE_HASH
          docker push $REGISTRY_URL:$CIRCLE_SHA1

workflows:
  version: 2
  metadata:
    jobs:
      - build
      - release_image:
          name: "release image"
          filters:
            tags:
              only:
                - /^v\d+.\d+.\d+.*/
            branches:
              ignore:
                - /.*/
